<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bidangminat_model extends CI_Model
{

    public $table = 'bidangminat';
    public $id = 'id_bidangminat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    //join bidang minat dengan matakuliah
function join_mk()
{
    $this->db->join('matakuliah', 'matakuliah.id_mk = bidangminat.id_mk');
    $this->db->join('minat', 'minat.id_minat = bidangminat.id_minat');
    return $this->db->get('bidangminat')->result();
}
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
         $this->db->join('matakuliah', 'matakuliah.id_mk = bidangminat.id_mk');
    $this->db->join('minat', 'minat.id_minat = bidangminat.id_minat');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_bidangminat', $q);
	$this->db->or_like('kode_mk', $q);
	$this->db->or_like('nama_bidangminat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_bidangminat', $q);
	$this->db->or_like('kode_mk', $q);
	$this->db->or_like('nama_bidangminat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bidangminat_model.php */
/* Location: ./application/models/Bidangminat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-16 04:54:13 */
/* http://harviacode.com */