<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bidangminat_bersyarat_model extends CI_Model
{

    public $table = 'bidangminat_bersyarat';
    public $id    = 'id_bminat_syarat';
    public $order = 'DESC';
    public $id_mk = 'id_mk';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);

        $this->db->join('matakuliah', 'matakuliah.id_mk = bidangminat_bersyarat.id_mk');
        $this->db->join('minat', 'minat.id_minat = bidangminat_bersyarat.id_minat');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
         $this->db->join('matakuliah', 'matakuliah.id_mk = bidangminat_bersyarat.id_mk');
        $this->db->join('minat', 'minat.id_minat = bidangminat_bersyarat.id_minat');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    
    $this->db->like('id_bminat_syarat', $q);
	$this->db->or_like('id_minat', $q);
	$this->db->or_like('id_mk', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_bminat_syarat', $q);
	    $this->db->or_like('id_minat', $q);
	    $this->db->or_like('id_mk', $q);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bidangminat_bersyarat_model.php */
/* Location: ./application/models/Bidangminat_bersyarat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-26 12:07:36 */
/* http://harviacode.com */