<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dpam_model extends CI_Model
{

    public $table = 'dpam';
    public $id = 'id_dpam';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_dpam', $q);
	$this->db->or_like('nidn', $q);
	$this->db->or_like('nama_dpam', $q);
	$this->db->or_like('pin_dpam', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_dpam', $q);
	$this->db->or_like('nidn', $q);
	$this->db->or_like('nama_dpam', $q);
	$this->db->or_like('pin_dpam', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

//all batas dpam

public function mhs_all()
{
    return $this->db->get('mahasiswa');
}


public function detail_mhs($id)
{
    $this->db->join('nilai', 'nilai.id_mahasiswa = mahasiswa.id_mahasiswa');
    $this->db->where('mahasiswa.id_mahasiswa', $id);
    return $this->db->get('mahasiswa')->row();
}













}

/* End of file Dpam_model.php */
/* Location: ./application/models/Dpam_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-16 04:54:14 */
/* http://harviacode.com */