<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jadwal_mk_model extends CI_Model
{

    public $table = 'jadwal_mk';
    public $id = 'id_jadwal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

function gel_join ()
{

 return $this->db->query('select
    mk.nama_matakuliah,
    jm.id_jadwal,
    jm.jam_masuk,
    jm.jam_selesai,
    rk.nama_ruangan,
    jm.hari,
    mt.id_mk_tawaran,
    s.nama_semester


    from jadwal_mk jm join mk_tawaran mt
    on mt.id_mk_tawaran=jm.id_mk_tawaran join matakuliah mk on mk.id_mk=mt.id_mk
join semester s on mt.id_semester = s.id_semester
    join ruang_kuliah rk on rk.id_ruang_kuliah=jm.id_ruang_kuliah')->result();
}


function get_mk_tawaran ()
{



 return $this->db->query('select * from mk_tawaran mt
        join semester s on s.id_semester=mt.id_semester

    join matakuliah mk on mt.id_mk=mk.id_mk')->result();


}

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {

    $this->db->like('id_jadwal', $q);
	$this->db->or_like('id_mk', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('jam_masuk', $q);
	$this->db->or_like('jam_selesai', $q);
	$this->db->or_like('ruangan', $q);
	$this->db->or_like('hari', $q);
	$this->db->from($this->table);
    return $this->db->count_all_results();

    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)

    {


    $this->db->order_by($this->id, $this->order);
    $this->db->like('id_jadwal', $q);
	$this->db->or_like('id_mk', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('jam_masuk', $q);
	$this->db->or_like('jam_selesai', $q);
	$this->db->or_like('ruangan', $q);
	$this->db->or_like('hari', $q);
	$this->db->limit($limit, $start);

    return $this->db->get($this->table)->result();

    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jadwal_mk_model.php */
/* Location: ./application/models/Jadwal_mk_model.php*/
/* Please DO NOT modify this information :*/
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-05 12:56:45 */
/* http://harviacode.com */
