<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kapasitas_kelas_model extends CI_Model
{

    public $table = 'kapasitas_kelas';
    public $id = 'id_kapasitas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

public function kelas()
{
            $data = $this->db->get('kelas')->result();
          return $data;
}

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function kk_join ()
{

    $this->db->join('kelas k','k.id_kelas=kapasitas_kelas.id_kelas');

    return $this->db->get('kapasitas_kelas')->result();
    
}

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kapasitas', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('kapasitas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kapasitas', $q);
	$this->db->or_like('id_kelas', $q);
	$this->db->or_like('kapasitas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kapasitas_kelas_model.php */
/* Location: ./application/models/Kapasitas_kelas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-05 12:57:18 */
/* http://harviacode.com */