<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mk_syarat_model extends CI_Model
{

    public $table = 'mk_syarat';
    public $id = 'id_syarat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


public function syarat()
{
   $this->db->join('minat', 'minat.id_minat = bidangminat.id_minat');
          return $this->db->get('bidangminat');
}



    function join_all()
{
   // $this->db->join('semester','semester.id_semester = mk_syarat.id_semester');
    //$this->db->join('matakuliah','matakuliah.id_mk= mk_syarat.id_mk','cross');

   // $data = $this->db->get('mk_syarat');
    //return $data;



$this->db->select(' m.kode_mk,m.nama_matakuliah, mk.nama_matakuliah AS "syarat", s.nama_semester,id_syarat')
->from('mk_syarat ms')
->join('semester s','s.id_semester = ms.id_semester')
->join('matakuliah m', 'm.id_mk = ms.id_mk')
->join('matakuliah mk', 'mk.id_mk = ms.syarat' );

return $this->db->get();

}



    function join_minat()
{
    $this->db->join('matakuliah', 'matakuliah.id_mk = bidangminat.id_mk');
    $this->db->join('minat', 'minat.id_minat = bidangminat.id_minat');
    return $this->db->get('bidangminat')->result();
}

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {

$this->db->select(' m.nama_matakuliah, mk.nama_matakuliah AS "syarat", s.nama_semester,id_syarat')
->from('mk_syarat ms')
->join('semester s','s.id_semester = ms.id_semester')
->join('matakuliah m', 'm.id_mk = ms.id_mk')
->join('matakuliah mk', 'mk.id_mk = ms.syarat' );
        $this->db->where($this->id, $id);

        return $this->db->get()->row();
    }

function get_by_id_update($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }




    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_syarat', $q);
	$this->db->or_like('id_minat', $q);
	$this->db->or_like('syarat', $q);
	$this->db->or_like('prasyarat', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_syarat', $q);
	$this->db->or_like('id_bidangminat', $q);
	$this->db->or_like('id_nilai', $q);
	$this->db->or_like('nama_mk_syarat', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mk_syarat_model.php */
/* Location: ./application/models/Mk_syarat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-16 04:54:15 */
/* http://harviacode.com */
