<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mk_tawaran_model extends CI_Model
{

    public $table = 'mk_tawaran';
    public $id = 'id_mk_tawaran';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_mk_tawaran', $q);
	$this->db->or_like('id_mk', $q);
	$this->db->or_like('id_semester', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
     {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_mk_tawaran', $q);
	$this->db->or_like('id_mk', $q);
	$this->db->or_like('id_semester', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }



public function join_expert()
{

    $this->db->join('matakuliah mk', 'mk.id_mk = mk_tawaran.id_mk');
    $this->db->join('semester s', 's.id_semester = mk_tawaran.id_semester');
     $this->db->order_by('s.nama_semester', 'asc');
    return $this->db->get('mk_tawaran')->result_array();
}

public function join_expert_2()
{
    $this->db->join('matakuliah mk', 'mk.id_mk = mk_tawaran.id_mk');
    $this->db->join('semester s', 's.id_semester = mk_tawaran.id_semester');
    return $this->db->get('mk_tawaran')->result();
}


public function join_expert_replace()
{

    //$this->db->join('matakuliah mk', 'mk.id_mk = mk_tawaran.id_mk');
  //  $this->db->join('semester s', 's.id_semester = mk_tawaran.id_semester');

    return $this->db->query('SELECT * FROM mk_tawaran WHERE id_semester=11')->result();
}

public function join_expert_3()
{

$this->db->order_by('mk.kode_mk');

    return $this->db->get('matakuliah mk')->result();
}

// semester genap

public function semester_genap()
{

  return $this->db->query(
							'select * from mk_tawaran mt natural join matakuliah mk natural join semester natural left join nilai    where mt.id_mk in (Select id_mk from (Select id_mk from mk_tawaran mt
                            where mt.id_semester in (select id_semester from semester
                            where mod(nama_semester,2) !=1) Union Select id_mk from nilai
                            where nilai.akhir<=50 and nilai.id_mahasiswa=7) daftar
                            Where daftar.id_mk NOT IN (Select id_mk from nilai
                            where nilai.akhir>=50 and nilai.id_mahasiswa=7))'
							)->result_array();

}

public function semester_ganjil()
{

    return $this->db->query(
							'select * from mk_tawaran mt natural join matakuliah mk natural join semester natural left join nilai	where mt.id_mk in (Select id_mk from (Select id_mk from mk_tawaran mt
                            where mt.id_semester in (select id_semester from semester
                            where mod(nama_semester,2) !=0) Union Select id_mk from nilai
                            where nilai.akhir<=50 and nilai.id_mahasiswa=7) daftar
                            Where daftar.id_mk NOT IN (Select id_mk from nilai
                            where nilai.akhir>=50 and nilai.id_mahasiswa=7))'
							)->result_array();
}

/*
1. tampilkan semua matakuliah persemester ganjil dan genap
2. dan tampilkan juga matakuliah yang belum lulus
*/

}

/* End of file Mk_tawaran_model.php */
/* Location: ./application/models/Mk_tawaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-18 13:04:43 */
/* http://harviacode.com

	'select * from mk_tawaran mt
							join matakuliah mk on mk.id_mk = mt.id_mk
							join semester on semester.id_semester=mt.id_semester
							left join nilai on nilai.id_mk=mt.id_mk
							where mt.id_mk in (Select id_mk from (Select id_mk from mk_tawaran mt
							where mt.id_semester in (select id_semester from semester
							where mod(nama_semester,2) !=0) Union Select id_mk from nilai
							where nilai.akhir<=50 and nilai.id_mahasiswa=6) daftar
							Where daftar.id_mk NOT IN (Select id_mk from nilai
							where nilai.akhir>=50 and nilai.id_mahasiswa=6))'


Select id_mk from (Select id_mk from mk_tawaran union select id_semester from semester where mod(nama_semester,2) !=0 Union Select id_mk from nilai where akhir<=50 and id_mahasiswa=6) daftar Where daftar.id_mk NOT IN (Select id_mk from nilai where akhir>=50 and id_mahasiswa=6)
select mk.nama_matakuliah from matakuliah mk where mk.id_mk in(select mt.id_mk_tawaran from mk_tawaran mt)

*/
