<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nilai_model extends CI_Model
{

    public $table = 'nilai';
    public $id = 'id_nilai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

//    query count sks  select count(sks) as total_sks from nilai,matakuliah where nilai.id_mk=matakuliah.id_mk
    // select *,sum(sks) as total_sks from nilai natural join matakuliah,mahasiswa where matakuliah.id_mk = nilai.id_mk & mahasiswa.id_mahasiswa = nilai.id_mahasiswa

function count_sks()
{
    return $this->db->query('select *,sum(sks) as total_sks from nilai natural
							join matakuliah,mahasiswa where matakuliah.id_mk =
							nilai.id_mk && mahasiswa.id_mahasiswa = nilai.id_mahasiswa');
}
    //join data
    function data_nilai()
    {
        $this->db->order_by($this->id, $this->order);
     //   $this->db->join('mk_tawaran', 'mk_tawaran.id_mk_tawaran = nilai.id_mk_tawaran'); //matakuliah
		$this->db->join('matakuliah', 'matakuliah.id_mk= nilai.id_mk'); //matakuliah
        $this->db->join('mahasiswa', 'mahasiswa.id_mahasiswa = nilai.id_mahasiswa'); //mahasiswa
        $this->db->join('semester', 'semester.id_semester = nilai.id_semester'); //semester

      return  $this->db->get($this->table)->result();
    }

       function mutu($ids)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select('SUM(mutu) as total_mutu');
          //     $this->db->join('mahasiswa', 'mahasiswa.id_mahasiswa = nilai.id_mahasiswa'); //mahasiswa

      $this->db->where('id_mahasiswa', $ids);

      return  $this->db->get($this->table)->row();
    }


 function ips_sks($id)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select('SUM(sks) as total_sks');
          //     $this->db->join('mahasiswa', 'mahasiswa.id_mahasiswa = nilai.id_mahasiswa'); //mahasiswa

      $this->db->where('id_mahasiswa', $id);

      return  $this->db->get($this->table)->row();
    }
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {

        $this->db->join('matakuliah', 'matakuliah.id_mk = nilai.id_mk'); //matakuliah
        $this->db->join('mahasiswa', 'mahasiswa.id_mahasiswa = nilai.id_mahasiswa'); //mahasiswa
        $this->db->join('semester', 'semester.id_semester = nilai.id_semester'); //semester
$this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_nilai', $q);
	$this->db->or_like('id_mk_tawaran', $q);
	$this->db->or_like('id_mahasiswa', $q);
	$this->db->or_like('id_semester', $q);
	$this->db->or_like('tugas', $q);
	$this->db->or_like('uts', $q);
	$this->db->or_like('uas', $q);
	$this->db->or_like('akhir', $q);
	$this->db->or_like('huruf', $q);
	$this->db->or_like('total_sks', $q);
	$this->db->or_like('total_huruf', $q);
	$this->db->or_like('ip', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_nilai', $q);
	$this->db->or_like('id_mk_tawaran', $q);
	$this->db->or_like('id_mahasiswa', $q);
	$this->db->or_like('id_semester', $q);
	$this->db->or_like('tugas', $q);
	$this->db->or_like('uts', $q);
	$this->db->or_like('uas', $q);
	$this->db->or_like('akhir', $q);
	$this->db->or_like('huruf', $q);
	$this->db->or_like('total_sks', $q);
	$this->db->or_like('total_huruf', $q);
	$this->db->or_like('ip', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }








}

/* End of file Nilai_model.php */
/* Location: ./application/models/Nilai_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-06-16 11:20:24 */
/* http://harviacode.com */
