<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class SyaratBatasSksModel extends CI_Model
{

    public $table = 'syarat_batas_sks';
    public $id = 'id_mk_syarat_sks';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('matakuliah mk', 'mk.id_mk = syarat_batas_sks.id_mk');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_mk_syarat_sks', $q);
	$this->db->or_like('id_mk', $q);
	$this->db->or_like('batas_sks', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_mk_syarat_sks', $q);
	$this->db->or_like('id_mk', $q);
	$this->db->or_like('batas_sks', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file SyaratBatasSksModel.php */
/* Location: ./application/models/SyaratBatasSksModel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-07 19:33:13 */
/* http://harviacode.com */
